"""Stable internal models and SDK response conversion."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class User:
    """A Remnawave user (= Meridian client)."""

    uuid: str = ""
    short_uuid: str = ""
    username: str = ""
    vless_uuid: str = ""  # VLESS protocol UUID (used by Xray, differs from account UUID)
    status: str = ""  # "ACTIVE", "DISABLED", "LIMITED", "EXPIRED"
    used_traffic_bytes: int = 0
    traffic_limit_bytes: int = 0
    created_at: str = ""
    online_at: str = ""
    sub_revoked_at: str = ""
    _raw: dict[str, Any] = field(default_factory=dict, repr=False)


@dataclass
class Node:
    """A Remnawave proxy node."""

    uuid: str = ""
    name: str = ""
    address: str = ""
    port: int = 0
    is_connected: bool = False
    is_disabled: bool = False
    xray_version: str = ""
    traffic_used: int = 0
    _raw: dict[str, Any] = field(default_factory=dict, repr=False)


@dataclass
class Host:
    """A Remnawave host entry (direct address or relay)."""

    uuid: str = ""
    remark: str = ""
    address: str = ""
    port: int = 0
    sni: str = ""
    host: str = ""
    path: str = ""
    alpn: str = ""
    fingerprint: str = ""
    security_layer: str = "DEFAULT"
    config_profile_uuid: str = ""
    inbound_uuid: str = ""
    is_disabled: bool = False
    _raw: dict[str, Any] = field(default_factory=dict, repr=False)


@dataclass
class Inbound:
    """A Remnawave inbound (protocol definition)."""

    uuid: str = ""
    tag: str = ""
    type: str = ""  # "vless", "trojan", "shadowsocks"
    network: str = ""  # "tcp", "ws", "xhttp"
    security: str = ""  # "reality", "tls", "none"
    _raw: dict[str, Any] = field(default_factory=dict, repr=False)


@dataclass
class ConfigProfile:
    """A Remnawave config profile (Xray configuration template)."""

    uuid: str = ""
    name: str = ""
    _raw: dict[str, Any] = field(default_factory=dict, repr=False)


@dataclass
class NodeCredentials:
    """Connection credentials for a new node (generated by panel)."""

    uuid: str = ""
    secret_key: str = ""  # base64 JSON with mTLS certs
    _raw: dict[str, Any] = field(default_factory=dict, repr=False)


# ---------------------------------------------------------------------------
# SDK ↔ dataclass converters
# ---------------------------------------------------------------------------


def user_from_sdk(obj: Any) -> User:
    """Convert SDK UserResponseDto to our User dataclass.

    SDK Pydantic models declare fields as ``snake_case = Field(alias="camelCase")`` —
    Python attribute access requires snake_case. Reading the camelCase alias via
    ``getattr`` returns the default and silently drops data.
    """
    traffic = getattr(obj, "user_traffic", None)
    return User(
        uuid=str(getattr(obj, "uuid", "")),
        short_uuid=str(getattr(obj, "short_uuid", "") or ""),
        username=getattr(obj, "username", "") or "",
        vless_uuid=str(getattr(obj, "vless_uuid", "") or ""),
        status=str(getattr(obj, "status", "") or ""),
        used_traffic_bytes=int(getattr(traffic, "used_traffic_bytes", 0) or 0),
        traffic_limit_bytes=int(getattr(obj, "traffic_limit_bytes", 0) or 0),
        created_at=str(getattr(obj, "created_at", "") or ""),
        online_at=str(getattr(traffic, "online_at", "") or ""),
        sub_revoked_at=str(getattr(obj, "sub_revoked_at", "") or ""),
    )


def node_from_sdk(obj: Any) -> Node:
    """Convert SDK NodeResponseDto to our Node dataclass."""
    return Node(
        uuid=str(getattr(obj, "uuid", "")),
        name=getattr(obj, "name", "") or "",
        address=getattr(obj, "address", "") or "",
        port=int(getattr(obj, "port", 0) or 0),
        is_connected=bool(getattr(obj, "is_connected", False)),
        is_disabled=bool(getattr(obj, "is_disabled", False)),
        xray_version=getattr(obj, "xray_version", "") or "",
        traffic_used=int(getattr(obj, "traffic_used_bytes", 0) or 0),
    )


def host_from_sdk(obj: Any) -> Host:
    """Convert SDK HostResponseDto to our Host dataclass."""
    inbound = getattr(obj, "inbound", None)
    return Host(
        uuid=str(getattr(obj, "uuid", "")),
        remark=getattr(obj, "remark", "") or "",
        address=getattr(obj, "address", "") or "",
        port=int(getattr(obj, "port", 0) or 0),
        sni=getattr(obj, "sni", "") or "",
        host=getattr(obj, "host", "") or "",
        path=getattr(obj, "path", "") or "",
        alpn=str(getattr(obj, "alpn", "") or ""),
        fingerprint=getattr(obj, "fingerprint", "") or "",
        security_layer=enum_string(getattr(obj, "security_layer", "DEFAULT")),
        config_profile_uuid=str(getattr(inbound, "config_profile_uuid", "") or ""),
        # SDK field is `config_profile_inbound_uuid` (Pydantic snake_case for
        # the JSON alias `configProfileInboundUuid`). Mapped to our simpler
        # `inbound_uuid`. If a future SDK bump renames this field, the getattr
        # silently returns "" — keep this comment as a breadcrumb.
        inbound_uuid=str(getattr(inbound, "config_profile_inbound_uuid", "") or ""),
        is_disabled=bool(getattr(obj, "is_disabled", False)),
        _raw=sdk_to_dict(obj) if obj is not None else {},
    )


def inbound_from_sdk(obj: Any) -> Inbound:
    """Convert SDK inbound DTO to our Inbound dataclass."""
    return Inbound(
        uuid=str(getattr(obj, "uuid", "")),
        tag=getattr(obj, "tag", ""),
        type=getattr(obj, "type", ""),
        network=getattr(obj, "network", "") or "",
        security=getattr(obj, "security", "") or "",
    )


def config_profile_from_sdk(obj: Any) -> ConfigProfile:
    """Convert SDK ConfigProfileDto to our ConfigProfile dataclass."""
    return ConfigProfile(
        uuid=str(getattr(obj, "uuid", "")),
        name=getattr(obj, "name", ""),
        _raw=sdk_to_dict(obj) if obj is not None else {},
    )


def sdk_items(resp: Any, *, attr: str | None = None) -> list[Any]:
    """Extract list payloads from SDK responses with mixed shapes."""
    if resp is None:
        return []
    if attr:
        items = getattr(resp, attr, None)
        if isinstance(items, list):
            return items
    root = getattr(resp, "root", None)
    if isinstance(root, list):
        return root
    if isinstance(resp, list):
        return resp
    return []


def sdk_to_dict(obj: Any) -> Any:
    """Recursively convert SDK models to plain Python containers."""
    if hasattr(obj, "model_dump"):
        return obj.model_dump(mode="python")
    if isinstance(obj, list):
        return [sdk_to_dict(item) for item in obj]
    if isinstance(obj, tuple):
        return [sdk_to_dict(item) for item in obj]
    if isinstance(obj, dict):
        return {key: sdk_to_dict(value) for key, value in obj.items()}
    return obj


def enum_string(value: Any) -> str:
    """Return an enum's wire value or a plain string."""
    return str(getattr(value, "value", value) or "")


def parse_host(data: Any) -> Host:
    if not isinstance(data, dict):
        return Host()
    inbound = data.get("inbound")
    inbound = inbound if isinstance(inbound, dict) else {}
    return Host(
        uuid=data.get("uuid", ""),
        remark=data.get("remark", ""),
        address=data.get("address", ""),
        port=data.get("port", 0),
        sni=data.get("sni") or "",
        host=data.get("host") or "",
        path=data.get("path") or "",
        alpn=data.get("alpn") or "",
        fingerprint=data.get("fingerprint") or "",
        security_layer=enum_string(data.get("securityLayer", "DEFAULT")),
        config_profile_uuid=str(inbound.get("configProfileUuid") or ""),
        inbound_uuid=str(
            inbound.get("configProfileInboundUuid") or data.get("inboundUuid") or data.get("inbound_uuid") or ""
        ),
        is_disabled=data.get("isDisabled", False),
        _raw=data,
    )
