"""Helpers for executing canonical Remnawave Xray subscriptions."""

from __future__ import annotations

import copy
import json
import socket
from collections.abc import Iterable
from typing import Any

from meridian.remnawave import MeridianPanel, SubscriptionDocument

_PROXY_TAG_PREFIX = "MERIDIAN_PROXY"


def fetch_canonical_xray(
    panel: MeridianPanel,
    username: str,
) -> SubscriptionDocument:
    """Fetch the client document generated by Remnawave itself."""
    user = panel.get_user(username)
    if user is None or not user.short_uuid:
        raise ValueError(f"Remnawave user {username!r} has no subscription")
    return panel.fetch_subscription(
        user.short_uuid,
        client_type="xray-json",
    )


def parse_xray_subscription(content: str) -> dict[str, Any]:
    """Validate and decode a rendered canonical Xray document."""
    try:
        parsed = json.loads(content)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Canonical Xray subscription is not JSON: {exc}") from exc
    if not isinstance(parsed, dict):
        raise ValueError("Canonical Xray subscription must be an object")
    outbounds = parsed.get("outbounds")
    if not isinstance(outbounds, list):
        raise ValueError("Canonical Xray subscription has no outbounds")
    if not proxy_outbounds(parsed):
        raise ValueError("Canonical Xray subscription has no Meridian proxy outbounds")
    return parsed


def proxy_outbounds(
    config: dict[str, Any],
) -> list[dict[str, Any]]:
    """Return only Remnawave-injected Meridian proxy outbounds."""
    outbounds = config.get("outbounds")
    if not isinstance(outbounds, list):
        return []
    return [
        outbound
        for outbound in outbounds
        if isinstance(outbound, dict) and str(outbound.get("tag", "")).startswith(_PROXY_TAG_PREFIX)
    ]


def outbound_address(outbound: dict[str, Any]) -> str:
    """Read the first VLESS endpoint without inventing missing values."""
    settings = outbound.get("settings")
    if not isinstance(settings, dict):
        return ""
    destinations = settings.get("vnext")
    if not isinstance(destinations, list) or not destinations:
        return ""
    destination = destinations[0]
    if not isinstance(destination, dict):
        return ""
    return str(destination.get("address", ""))


def endpoint_addresses(config: dict[str, Any]) -> set[str]:
    """Return every concrete proxy address delivered by Remnawave."""
    return {address for outbound in proxy_outbounds(config) if (address := outbound_address(outbound))}


def select_outbound(
    config: dict[str, Any],
    address: str,
) -> str:
    """Select one canonical outbound by its delivered endpoint."""
    for outbound in proxy_outbounds(config):
        if outbound_address(outbound) == address:
            tag = outbound.get("tag")
            if isinstance(tag, str) and tag:
                return tag
    raise ValueError(f"Canonical subscription has no endpoint for {address}")


def route_only(
    config: dict[str, Any],
    outbound_tag: str,
) -> dict[str, Any]:
    """Pin traffic to one delivered outbound for path acceptance."""
    known_tags = {str(outbound.get("tag", "")) for outbound in proxy_outbounds(config)}
    if outbound_tag not in known_tags:
        raise ValueError(f"Canonical subscription has no outbound {outbound_tag!r}")
    selected = copy.deepcopy(config)
    routing = selected.setdefault("routing", {})
    if not isinstance(routing, dict):
        raise ValueError("Canonical Xray routing must be an object")
    routing["rules"] = [
        {
            "type": "field",
            "ip": ["geoip:private"],
            "outboundTag": "BLOCK",
        },
        {
            "type": "field",
            "network": "tcp,udp",
            "outboundTag": outbound_tag,
        },
    ]
    routing.pop("balancers", None)
    selected.pop("burstObservatory", None)
    selected.pop("observatory", None)
    return selected


def use_free_local_ports(
    config: dict[str, Any],
) -> tuple[dict[str, Any], int]:
    """Move canonical local listeners to free ports for repeatable tests."""
    selected = copy.deepcopy(config)
    inbounds = selected.get("inbounds")
    if not isinstance(inbounds, list):
        raise ValueError("Canonical Xray subscription has no inbounds")
    socks_port = 0
    for inbound in inbounds:
        if not isinstance(inbound, dict):
            continue
        port = _free_port()
        inbound["port"] = port
        if inbound.get("protocol") == "socks":
            socks_port = port
    if not socks_port:
        raise ValueError("Canonical Xray subscription has no SOCKS inbound")
    return selected, socks_port


def replace_user_ids(
    config: dict[str, Any],
    replacement: str,
) -> dict[str, Any]:
    """Corrupt delivered credentials without reconstructing endpoints."""
    selected = copy.deepcopy(config)
    replaced = 0
    for outbound in proxy_outbounds(selected):
        settings = outbound.get("settings")
        if not isinstance(settings, dict):
            continue
        destinations = settings.get("vnext")
        if not isinstance(destinations, list):
            continue
        for destination in destinations:
            if not isinstance(destination, dict):
                continue
            users = destination.get("users")
            if not isinstance(users, list):
                continue
            for user in users:
                if isinstance(user, dict) and "id" in user:
                    user["id"] = replacement
                    replaced += 1
    if not replaced:
        raise ValueError("Canonical Xray subscription contains no user IDs")
    return selected


def missing_addresses(
    config: dict[str, Any],
    expected: Iterable[str],
) -> set[str]:
    """Compare expected lab endpoints with canonical delivery."""
    return set(expected) - endpoint_addresses(config)


def _free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as listener:
        listener.bind(("127.0.0.1", 0))
        return int(listener.getsockname()[1])
