"""Helpers for validating and executing canonical Remnawave subscriptions."""

from __future__ import annotations

import base64
import binascii
import copy
import json
import socket
from collections.abc import Iterable
from typing import Any
from urllib.parse import urlsplit
from uuid import UUID

import yaml

from meridian.remnawave import XRAY_JSON_CLIENT_TYPE, MeridianPanel, SubscriptionDocument

_PROXY_TAG_PREFIX = "MERIDIAN_PROXY"


def fetch_canonical_xray(
    panel: MeridianPanel,
    username: str,
) -> SubscriptionDocument:
    """Fetch the client document generated by Remnawave itself."""
    user = panel.get_user(username)
    if user is None or not user.short_uuid:
        raise ValueError(f"Remnawave user {username!r} has no subscription")
    return panel.fetch_subscription(
        user.short_uuid,
        client_type=XRAY_JSON_CLIENT_TYPE,
    )


def parse_xray_subscription(content: str) -> dict[str, Any]:
    """Validate and decode a rendered canonical Xray document."""
    try:
        parsed = json.loads(content)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Canonical Xray subscription is not JSON: {exc}") from exc
    if isinstance(parsed, list):
        if len(parsed) != 1:
            raise ValueError("Canonical Xray subscription must contain exactly one config")
        parsed = parsed[0]
    if not isinstance(parsed, dict):
        raise ValueError("Canonical Xray subscription must be an object")
    outbounds = parsed.get("outbounds")
    if not isinstance(outbounds, list):
        raise ValueError("Canonical Xray subscription has no outbounds")
    if not proxy_outbounds(parsed):
        raise ValueError("Canonical Xray subscription has no Meridian proxy outbounds")
    return parsed


def parse_base64_subscription(content: str) -> list[str]:
    """Decode a canonical Base64 subscription into validated proxy URLs."""
    encoded = "".join(content.split())
    if not encoded:
        raise ValueError("Canonical Base64 subscription is empty")
    encoded += "=" * (-len(encoded) % 4)
    try:
        decoded = base64.b64decode(encoded, validate=True).decode("utf-8")
    except (binascii.Error, UnicodeDecodeError) as exc:
        raise ValueError("Canonical Base64 subscription is not valid Base64 UTF-8") from exc
    urls = [line.strip() for line in decoded.splitlines() if line.strip()]
    if not urls:
        raise ValueError("Canonical Base64 subscription contains no proxy URLs")
    for url in urls:
        parsed = urlsplit(url)
        if parsed.scheme not in {"vless", "hysteria2"}:
            raise ValueError(f"Canonical Base64 subscription contains unsupported URL scheme {parsed.scheme!r}")
        try:
            port = parsed.port
        except ValueError as exc:
            raise ValueError("Canonical Base64 subscription contains an invalid endpoint port") from exc
        if not parsed.hostname or port is None or not 1 <= port <= 65535:
            raise ValueError("Canonical Base64 subscription contains an incomplete endpoint")
        if parsed.scheme == "vless":
            try:
                UUID(parsed.username or "")
            except ValueError as exc:
                raise ValueError("Canonical Base64 subscription contains an invalid VLESS UUID") from exc
    return urls


def base64_endpoint_addresses(urls: Iterable[str]) -> set[str]:
    """Return endpoint addresses from validated Base64 subscription URLs."""
    return {address for url in urls if (address := urlsplit(url).hostname)}


def base64_vless_user_ids(urls: Iterable[str]) -> set[str]:
    """Return normalized VLESS UUIDs from validated Base64 URLs."""
    return {str(UUID(parsed.username or "")) for url in urls if (parsed := urlsplit(url)).scheme == "vless"}


def parse_mihomo_subscription(content: str) -> dict[str, Any]:
    """Parse a canonical Mihomo document and validate its fallback graph."""
    try:
        parsed = yaml.safe_load(content)
    except yaml.YAMLError as exc:
        raise ValueError(f"Canonical Mihomo subscription is not YAML: {exc}") from exc
    if not isinstance(parsed, dict):
        raise ValueError("Canonical Mihomo subscription must be an object")
    proxies = parsed.get("proxies")
    if not isinstance(proxies, list) or not proxies:
        raise ValueError("Canonical Mihomo subscription has no proxies")

    proxy_names: set[str] = set()
    for proxy in proxies:
        if not isinstance(proxy, dict):
            raise ValueError("Canonical Mihomo subscription contains a malformed proxy")
        name = proxy.get("name")
        proxy_type = proxy.get("type")
        server = proxy.get("server")
        try:
            port = int(proxy.get("port"))
        except (TypeError, ValueError) as exc:
            raise ValueError("Canonical Mihomo subscription contains an invalid proxy port") from exc
        if not isinstance(name, str) or not name or name in proxy_names:
            raise ValueError("Canonical Mihomo subscription proxy names must be nonempty and unique")
        if not isinstance(proxy_type, str) or not proxy_type or not isinstance(server, str) or not server:
            raise ValueError("Canonical Mihomo subscription contains an incomplete proxy")
        if not 1 <= port <= 65535:
            raise ValueError("Canonical Mihomo subscription contains an invalid proxy port")
        if proxy_type == "vless":
            try:
                UUID(str(proxy.get("uuid", "")))
            except ValueError as exc:
                raise ValueError("Canonical Mihomo subscription contains an invalid VLESS UUID") from exc
        proxy_names.add(name)

    groups = parsed.get("proxy-groups")
    if not isinstance(groups, list) or not groups:
        raise ValueError("Canonical Mihomo subscription has no proxy groups")
    fallback_names: set[str] = set()
    for group in groups:
        if not isinstance(group, dict) or group.get("type") != "fallback":
            continue
        name = group.get("name")
        members = group.get("proxies")
        if not isinstance(name, str) or not name or not isinstance(members, list) or not members:
            continue
        if not all(isinstance(member, str) and member in proxy_names for member in members):
            raise ValueError("Canonical Mihomo fallback references an unknown proxy")
        fallback_names.add(name)
    if not fallback_names:
        raise ValueError("Canonical Mihomo subscription has no populated fallback group")

    rules = parsed.get("rules")
    if not isinstance(rules, list) or not any(
        isinstance(rule, str) and rule.startswith("MATCH,") and rule.removeprefix("MATCH,") in fallback_names
        for rule in rules
    ):
        raise ValueError("Canonical Mihomo subscription does not route through its fallback group")
    return parsed


def mihomo_endpoint_addresses(config: dict[str, Any]) -> set[str]:
    """Return endpoint addresses from a validated Mihomo document."""
    proxies = config.get("proxies", [])
    return {
        str(proxy["server"])
        for proxy in proxies
        if isinstance(proxy, dict) and isinstance(proxy.get("server"), str) and proxy["server"]
    }


def mihomo_vless_user_ids(config: dict[str, Any]) -> set[str]:
    """Return normalized VLESS UUIDs from a validated Mihomo document."""
    return {
        str(UUID(str(proxy["uuid"])))
        for proxy in config.get("proxies", [])
        if isinstance(proxy, dict) and proxy.get("type") == "vless"
    }


def proxy_outbounds(
    config: dict[str, Any],
) -> list[dict[str, Any]]:
    """Return only Remnawave-injected Meridian proxy outbounds."""
    outbounds = config.get("outbounds")
    if not isinstance(outbounds, list):
        return []
    return [
        outbound
        for outbound in outbounds
        if isinstance(outbound, dict) and str(outbound.get("tag", "")).startswith(_PROXY_TAG_PREFIX)
    ]


def xray_vless_user_ids(config: dict[str, Any]) -> set[str]:
    """Return normalized VLESS UUIDs from canonical Xray proxy outbounds."""
    return {
        str(UUID(str(user["id"])))
        for outbound in proxy_outbounds(config)
        if outbound.get("protocol") == "vless"
        for destination in outbound.get("settings", {}).get("vnext", [])
        if isinstance(destination, dict)
        for user in destination.get("users", [])
        if isinstance(user, dict) and user.get("id")
    }


def outbound_address(outbound: dict[str, Any]) -> str:
    """Read the first VLESS endpoint without inventing missing values."""
    settings = outbound.get("settings")
    if not isinstance(settings, dict):
        return ""
    destinations = settings.get("vnext")
    if not isinstance(destinations, list) or not destinations:
        return ""
    destination = destinations[0]
    if not isinstance(destination, dict):
        return ""
    return str(destination.get("address", ""))


def endpoint_addresses(config: dict[str, Any]) -> set[str]:
    """Return every concrete proxy address delivered by Remnawave."""
    return {address for outbound in proxy_outbounds(config) if (address := outbound_address(outbound))}


def select_outbound(
    config: dict[str, Any],
    address: str,
) -> str:
    """Select one canonical outbound by its delivered endpoint."""
    for outbound in proxy_outbounds(config):
        if outbound_address(outbound) == address:
            tag = outbound.get("tag")
            if isinstance(tag, str) and tag:
                return tag
    raise ValueError(f"Canonical subscription has no endpoint for {address}")


def route_only(
    config: dict[str, Any],
    outbound_tag: str,
) -> dict[str, Any]:
    """Pin traffic to one delivered outbound for path acceptance."""
    known_tags = {str(outbound.get("tag", "")) for outbound in proxy_outbounds(config)}
    if outbound_tag not in known_tags:
        raise ValueError(f"Canonical subscription has no outbound {outbound_tag!r}")
    selected = copy.deepcopy(config)
    routing = selected.setdefault("routing", {})
    if not isinstance(routing, dict):
        raise ValueError("Canonical Xray routing must be an object")
    routing["rules"] = [
        {
            "type": "field",
            "ip": ["geoip:private"],
            "outboundTag": "BLOCK",
        },
        {
            "type": "field",
            "network": "tcp,udp",
            "outboundTag": outbound_tag,
        },
    ]
    routing.pop("balancers", None)
    selected.pop("burstObservatory", None)
    selected.pop("observatory", None)
    return selected


def use_free_local_ports(
    config: dict[str, Any],
) -> tuple[dict[str, Any], int]:
    """Move canonical local listeners to free ports for repeatable tests."""
    selected = copy.deepcopy(config)
    inbounds = selected.get("inbounds")
    if not isinstance(inbounds, list):
        raise ValueError("Canonical Xray subscription has no inbounds")
    socks_port = 0
    used_ports: set[int] = set()
    for inbound in inbounds:
        if not isinstance(inbound, dict):
            continue
        port = _free_port()
        while port in used_ports:
            port = _free_port()
        used_ports.add(port)
        inbound["port"] = port
        if inbound.get("protocol") == "socks":
            socks_port = port
    if not socks_port:
        raise ValueError("Canonical Xray subscription has no SOCKS inbound")
    return selected, socks_port


def replace_user_ids(
    config: dict[str, Any],
    replacement: str,
) -> dict[str, Any]:
    """Corrupt delivered credentials without reconstructing endpoints."""
    selected = copy.deepcopy(config)
    replaced = 0
    for outbound in proxy_outbounds(selected):
        settings = outbound.get("settings")
        if not isinstance(settings, dict):
            continue
        destinations = settings.get("vnext")
        if not isinstance(destinations, list):
            continue
        for destination in destinations:
            if not isinstance(destination, dict):
                continue
            users = destination.get("users")
            if not isinstance(users, list):
                continue
            for user in users:
                if isinstance(user, dict) and "id" in user:
                    user["id"] = replacement
                    replaced += 1
    if not replaced:
        raise ValueError("Canonical Xray subscription contains no user IDs")
    return selected


def missing_addresses(
    config: dict[str, Any],
    expected: Iterable[str],
) -> set[str]:
    """Compare expected lab endpoints with canonical delivery."""
    return set(expected) - endpoint_addresses(config)


def _free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as listener:
        listener.bind(("127.0.0.1", 0))
        return int(listener.getsockname()[1])
